job.type: search
search.type: ax
search.on_error: continue
dataset.name: hetionet-fold1-subset-with-inverse

train:
  max_epochs: 400
  auto_correct: True

valid:
  every: 2
  metric: mrr_avg_val
  early_stopping:
    patience: 3

eval:
  type: CxDRankingHetionetAvg

user:
  fold: 1
  dataset_variant: subset-with-inverse

model: reciprocal_relations_model
reciprocal_relations_model.base_model.type: conve # redundant since also default
conve.round_dim: true
negative_sampling.num_samples.s: 0
conve.entity_embedder.regularize_weight: 0.0
conve.relation_embedder.regularize_weight: 0.0
conve.entity_embedder.dropout: 0.19
conve.relation_embedder.dropout: 0.09
negative_sampling.num_samples.o: 1000

lookup_embedder.dim: 256
lookup_embedder.regularize_args.weighted: False
lookup_embedder.initialize: 'xavier_normal_'
lookup_embedder.initialize_args.xavier_normal_.gain: 1.0

train: 
  auto_correct: true
  type: negative_sampling
  batch_size: 40
  optimizer_args.lr: 0.34
  optimizer: 'Adagrad'
  lr_scheduler: 'ReduceLROnPlateau'
  lr_scheduler_args.mode: 'max'
  lr_scheduler_args.patience: 5
  lr_scheduler_args.factor: 0.95
  lr_scheduler_args.threshold: 0.0
