1vsAll:
  class_name: TrainingJob1vsAll
KvsAll:
  class_name: TrainingJobKvsAll
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
MyJob:
  class_name: MyJob
  type: EvaluationJob
ax_search:
  class_name: AxSearchJob
  num_sobol_trials: 30
  num_trials: 30
  parameter_constraints: []
  parameters:
  - name: model
    type: fixed
    value: transe
  - name: train.type
    type: fixed
    value: negative_sampling
  - name: train.batch_size
    type: choice
    values:
    - 128
    - 256
  - name: train.optimizer
    type: choice
    values:
    - Adam
    - Adagrad
  - bounds:
    - 0.0001
    - 1.0
    log_scale: true
    name: train.optimizer_args.lr
    type: range
  - name: train.lr_scheduler
    type: fixed
    value: ReduceLROnPlateau
  - name: train.lr_scheduler_args.mode
    type: fixed
    value: max
  - name: train.lr_scheduler_args.factor
    type: fixed
    value: 0.95
  - name: train.lr_scheduler_args.threshold
    type: fixed
    value: 0.0001
  - bounds:
    - 0
    - 10
    name: train.lr_scheduler_args.patience
    type: range
  - name: lookup_embedder.dim
    type: choice
    values:
    - 64
    - 128
    - 256
  - name: lookup_embedder.initialize
    type: fixed
    value: xavier_normal_
  - name: lookup_embedder.initialize_args.xavier_normal_.gain
    type: fixed
    value: 1.0
  - name: lookup_embedder.regularize
    type: choice
    values:
    - ''
    - l2
  - name: lookup_embedder.regularize_args.weighted
    type: choice
    values:
    - true
    - false
  - bounds:
    - 1.0e-20
    - 1.0e-05
    name: transe.entity_embedder.regularize_weight
    type: range
  - bounds:
    - 1.0e-20
    - 1.0e-05
    name: transe.relation_embedder.regularize_weight
    type: range
  - bounds:
    - 0.0
    - 0.5
    name: transe.entity_embedder.dropout
    type: range
  - bounds:
    - 0.0
    - 0.5
    name: transe.relation_embedder.dropout
    type: range
  - bounds:
    - 1
    - 1000
    log_scale: true
    name: negative_sampling.num_negatives_s
    type: range
  - bounds:
    - 1
    - 1000
    log_scale: true
    name: negative_sampling.num_negatives_o
    type: range
  - name: transe.l_norm
    type: choice
    values:
    - 1.0
    - 2.0
  - name: transe.entity_embedder.normalize.p
    type: choice
    values:
    - -1.0
    - 2.0
  - name: transe.relation_embedder.normalize.p
    type: choice
    values:
    - -1.0
    - 2.0
  sobol_seed: 0
console:
  format: {}
  quiet: false
conve:
  2D_aspect_ratio: 2
  class_name: ConvE
  convolution_bias: true
  entity_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  feature_map_dropout: 0.2
  filter_size: 3
  padding: 0
  projection_dropout: 0.3
  relation_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  round_dim: false
  stride: 1
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      size: 11902
      split_type: test
      type: triples
    test_without_unseen:
      filename: test_without_unseen.del
      size: 11894
      split_type: test
      type: triples
    train:
      filename: train.del
      size: 10946400
      split_type: train
      type: triples
    train_sample:
      filename: train_sample.del
      size: 11878
      split_type: train
      type: triples
    valid:
      filename: valid.del
      size: 11878
      split_type: valid
      type: triples
    valid_without_unseen:
      filename: valid_without_unseen.del
      size: 11872
      split_type: valid
      type: triples
  name: .
  num_entities: 71467
  num_relations: 192
  pickle: true
entity_ranking:
  chunk_size: -1
  class_name: EntityRankingJob
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: false
  tie_handling:
    atol: 1e-05
    rtol: 1e-04
    type: rounded_mean_rank
eval:
  batch_size: 100
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: epoch
  type: MyJob
grid_search:
  class_name: GridSearchJob
  parameters:
    +++: +++
  run: true
import:
- transe
- reciprocal_relations_model
- MyFile
job:
  device: cuda:0
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 256
  dropout: 0.0
  initialize: xavier_normal_
  initialize_args:
    +++: +++
    xavier_normal_:
      gain: 1.0
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 2
    weighted: false
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false
manual_search:
  class_name: ManualSearchJob
  configurations: []
  run: true
model: transe
modules:
- kge.model
- kge.job
- kge.model.embedder
negative_sampling:
  class_name: TrainingJobNegativeSampling
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: auto
  num_samples:
    o: 110
    p: 0
    s: 3
  sampling_type: uniform
  shared: false
  shared_type: default
  with_replacement: true
random_seed:
  default: -1
  numba: -1
  numpy: -1
  python: -1
  torch: -1
reciprocal_relations_model:
  base_model:
    +++: +++
    type: transe
  class_name: ReciprocalRelationsModel
search:
  device_pool:
  - cuda:0
  - cuda:1
  num_workers: 2
  on_error: continue
  type: ax_search
train:
  abort_on_nan: true
  auto_correct: true
  batch_size: 256
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: kl
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  lr_warmup: 0
  max_epochs: 400
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.019739391547314692
      type: Adagrad
  pin_memory: false
  split: train
  subbatch_auto_tune: false
  subbatch_size: -1
  trace_level: epoch
  type: negative_sampling
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
transe:
  class_name: TransE
  entity_embedder:
    +++: +++
    dropout: 0.064239545725286
    normalize:
      p: 2.0
    regularize_weight: 1.8529932573437773e-06
    type: lookup_embedder
  l_norm: 1.0
  relation_embedder:
    +++: +++
    dropout: 0.0006243246607482433
    normalize:
      p: -1.0
    regularize_weight: 1.5290994476527061e-06
    type: lookup_embedder
user:
  +++: +++
  dataset: drkg
  dataset_variant: subset-with-inverse
valid:
  early_stopping:
    patience: 3
    threshold:
      epochs: 0
      metric_value: 0.0
  every: 2
  metric: mrr_avg_val
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch
